update 3.0.0

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -102,97 +102,97 @@ jobs:
           path: ${{ env.harvester_artifact_path }}
           if-no-files-found: error
 
-  build-harvester-linux-arm64:
-    runs-on: [ARM64, Linux]
-    container:
-      image: ghcr.io/chik-network/build-images/manylinux2014_cuda_aarch64:sha-e545a1e7e0dffb82a224518aa96424e665b848e5
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v3
+  # build-harvester-linux-arm64:
+  #   runs-on: [ARM64, Linux]
+  #   container:
+  #     image: ghcr.io/chik-network/build-images/manylinux2014_cuda_aarch64:sha-e545a1e7e0dffb82a224518aa96424e665b848e5
+  #   steps:
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@v3
 
-      - name: Set Env
-        uses: Chik-Network/actions/setjobenv@main
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Set Env
+  #       uses: Chik-Network/actions/setjobenv@main
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Cache DNF packages
-        uses: actions/cache@v3
-        with:
-          path: /var/cache/dnf
-          key: ${{ runner.os }}-dnf-${{ hashFiles('**/your-build-file') }}
-          restore-keys: |
-            ${{ runner.os }}-dnf-
+  #     - name: Cache DNF packages
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: /var/cache/dnf
+  #         key: ${{ runner.os }}-dnf-${{ hashFiles('**/your-build-file') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-dnf-
 
-      - name: Get Version Number
-        id: version_number
-        shell: bash
-        run: ./.github/actions/get-version.sh centos arm64
+  #     - name: Get Version Number
+  #       id: version_number
+  #       shell: bash
+  #       run: ./.github/actions/get-version.sh centos arm64
 
-      - name: Install Prerequisites
-        shell: bash
-        run: |
-          set -eo pipefail
-          export module_platform_id=platform:el9
-          export MODULE_PLATFORM_ID=platform:el9
-          export PLATFORM_ID=platform:el9
-          uname -a
-          cat /etc/os-release
-          yum install -y dnf
-          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
-          dnf install -y dnf-plugins-core
-          dnf makecache
-          dnf install -y kernel-headers.aarch64 kernel-devel.aarch64 tar bzip2 make automake gcc gcc-c++ pciutils elfutils-libelf-devel libglvnd-opengl libglvnd-glx libglvnd-devel acpid pkgconfig dkms
-          dnf install -y cmake
-          dnf group install -y "Development Tools"
-          dnf install -y gmp-devel numactl-devel make git wget sed
+  #     - name: Install Prerequisites
+  #       shell: bash
+  #       run: |
+  #         set -eo pipefail
+  #         export module_platform_id=platform:el9
+  #         export MODULE_PLATFORM_ID=platform:el9
+  #         export PLATFORM_ID=platform:el9
+  #         uname -a
+  #         cat /etc/os-release
+  #         yum install -y dnf
+  #         dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
+  #         dnf install -y dnf-plugins-core
+  #         dnf makecache
+  #         dnf install -y kernel-headers.aarch64 kernel-devel.aarch64 tar bzip2 make automake gcc gcc-c++ pciutils elfutils-libelf-devel libglvnd-opengl libglvnd-glx libglvnd-devel acpid pkgconfig dkms
+  #         dnf install -y cmake
+  #         dnf group install -y "Development Tools"
+  #         dnf install -y gmp-devel numactl-devel make git wget sed
 
-      - name: Build Harvester
-        shell: bash
-        run: |
-          export artifact_name="green_reaper-v${{ env.BB_VERSION }}-linux-ARM64.tar.gz"
-          echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
-          # emits env.harvester_artifact_path
-          bash .github/actions/build-harvester.sh --artifact "${artifact_name}"
+  #     - name: Build Harvester
+  #       shell: bash
+  #       run: |
+  #         export artifact_name="green_reaper-v${{ env.BB_VERSION }}-linux-ARM64.tar.gz"
+  #         echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
+  #         # emits env.harvester_artifact_path
+  #         bash .github/actions/build-harvester.sh --artifact "${artifact_name}"
 
-      - name: Upload Harvester Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.harvester_artifact_name }}
-          path: ${{ env.harvester_artifact_path }}
-          if-no-files-found: error
+  #     - name: Upload Harvester Artifact
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.harvester_artifact_name }}
+  #         path: ${{ env.harvester_artifact_path }}
+  #         if-no-files-found: error
 
-  build-harvester-macos-arm64:
-    runs-on: [macos, arm64]
-    steps:
-      - name: Cleanup Environment
-        uses: Chik-Network/actions/clean-workspace@main
+  # build-harvester-macos-arm64:
+  #   runs-on: [macos, arm64]
+  #   steps:
+  #     - name: Cleanup Environment
+  #       uses: Chik-Network/actions/clean-workspace@main
 
-      - name: Checkout Repo
-        uses: actions/checkout@v3
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@v3
 
-      - name: Set Env
-        uses: Chik-Network/actions/setjobenv@main
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Set Env
+  #       uses: Chik-Network/actions/setjobenv@main
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Get Version Number
-        id: version_number
-        run: bash -e .github/actions/get-version.sh macos arm64
+  #     - name: Get Version Number
+  #       id: version_number
+  #       run: bash -e .github/actions/get-version.sh macos arm64
 
-      - name: Build Harvester
-        shell: bash
-        run: |
-          export artifact_name="green_reaper-v${{ env.BB_VERSION }}-macos-arm64.tar.gz"
-          echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
-          # emits env.harvester_artifact_path
-          bash .github/actions/build-harvester.sh --artifact "${artifact_name}"
+  #     - name: Build Harvester
+  #       shell: bash
+  #       run: |
+  #         export artifact_name="green_reaper-v${{ env.BB_VERSION }}-macos-arm64.tar.gz"
+  #         echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
+  #         # emits env.harvester_artifact_path
+  #         bash .github/actions/build-harvester.sh --artifact "${artifact_name}"
 
-      - name: Upload Harvester Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.harvester_artifact_name }}
-          path: ${{ env.harvester_artifact_path }}
-          if-no-files-found: error
+  #     - name: Upload Harvester Artifact
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.harvester_artifact_name }}
+  #         path: ${{ env.harvester_artifact_path }}
+  #         if-no-files-found: error
 
   build-harvester-macos-x86-64:
     runs-on: macOS-11
@@ -336,94 +336,94 @@ jobs:
           path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME_CUDA }}
           if-no-files-found: error
 
-  build-bladebit-centos-arm64:
-    runs-on: [ARM64, Linux]
-    container:
-      image: quay.io/centos/centos:stream8
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v3
+  # build-bladebit-centos-arm64:
+  #   runs-on: [ARM64, Linux]
+  #   container:
+  #     image: quay.io/centos/centos:stream8
+  #   steps:
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@v3
 
-      - name: Set Env
-        uses: Chik-Network/actions/setjobenv@main
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Set Env
+  #       uses: Chik-Network/actions/setjobenv@main
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Get Version Number
-        id: version_number
-        run: .github/actions/get-version.sh centos arm64
+  #     - name: Get Version Number
+  #       id: version_number
+  #       run: .github/actions/get-version.sh centos arm64
 
-      - name: Install Prerequisites
-        run: |
-          dnf install -y gcc-toolset-9-gcc gcc-toolset-9-gcc-c++ \
-            cmake gmp-devel numactl-devel make git
+  #     - name: Install Prerequisites
+  #       run: |
+  #         dnf install -y gcc-toolset-9-gcc gcc-toolset-9-gcc-c++ \
+  #           cmake gmp-devel numactl-devel make git
 
-      - name: Build
-        run: |
-          source /opt/rh/gcc-toolset-9/enable
-          .github/actions/build-asset-unix.sh --artifact ${{ env.BB_ARTIFACT_NAME }} --version ${{ env.BB_VERSION }}
+  #     - name: Build
+  #       run: |
+  #         source /opt/rh/gcc-toolset-9/enable
+  #         .github/actions/build-asset-unix.sh --artifact ${{ env.BB_ARTIFACT_NAME }} --version ${{ env.BB_VERSION }}
 
-      - name: Upload Artifact CentOS ARM64
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.BB_ARTIFACT_NAME }}
-          path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME }}
-          if-no-files-found: error
+  #     - name: Upload Artifact CentOS ARM64
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BB_ARTIFACT_NAME }}
+  #         path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME }}
+  #         if-no-files-found: error
 
-  build-bladebit-cuda-linux-arm64:
-    runs-on: [ARM64, Linux]
-    container:
-      image: chiknetwork/ubuntu-20.04-builder:latest
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v3
+  # build-bladebit-cuda-linux-arm64:
+  #   runs-on: [ARM64, Linux]
+  #   container:
+  #     image: chiknetwork/ubuntu-20.04-builder:latest
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #   steps:
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@v3
 
-      - name: Set Env
-        uses: Chik-Network/actions/setjobenv@main
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Set Env
+  #       uses: Chik-Network/actions/setjobenv@main
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Get Version Number
-        id: version_number
-        run: .github/actions/get-version.sh ubuntu arm64
+  #     - name: Get Version Number
+  #       id: version_number
+  #       run: .github/actions/get-version.sh ubuntu arm64
 
-      - name: Install Prerequisites
-        run: |
-          export DEBIAN_FRONTEND=noninteractive
-          apt update
-          apt install -y build-essential git libgmp-dev libnuma-dev
-      - name: Setup CUDA
-        run: |
-          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-ubuntu2004.pin
-          mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
-          wget https://developer.download.nvidia.com/compute/cuda/12.1.1/local_installers/cuda-repo-ubuntu2004-12-1-local_12.1.1-530.30.02-1_arm64.deb
-          dpkg -i cuda-repo-ubuntu2004-12-1-local_12.1.1-530.30.02-1_arm64.deb
-          cp /var/cuda-repo-ubuntu2004-12-1-local/cuda-*-keyring.gpg /usr/share/keyrings/
-          apt-get update
-          DEBIAN_FRONTEND=noninteractive apt-get -y install cuda
+  #     - name: Install Prerequisites
+  #       run: |
+  #         export DEBIAN_FRONTEND=noninteractive
+  #         apt update
+  #         apt install -y build-essential git libgmp-dev libnuma-dev
+  #     - name: Setup CUDA
+  #       run: |
+  #         wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-ubuntu2004.pin
+  #         mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
+  #         wget https://developer.download.nvidia.com/compute/cuda/12.1.1/local_installers/cuda-repo-ubuntu2004-12-1-local_12.1.1-530.30.02-1_arm64.deb
+  #         dpkg -i cuda-repo-ubuntu2004-12-1-local_12.1.1-530.30.02-1_arm64.deb
+  #         cp /var/cuda-repo-ubuntu2004-12-1-local/cuda-*-keyring.gpg /usr/share/keyrings/
+  #         apt-get update
+  #         DEBIAN_FRONTEND=noninteractive apt-get -y install cuda
 
-      - name: Build
-        run: .github/actions/build-asset-unix.sh --artifact ${{ env.BB_ARTIFACT_NAME }} --version ${{env.BB_VERSION}}
+  #     - name: Build
+  #       run: .github/actions/build-asset-unix.sh --artifact ${{ env.BB_ARTIFACT_NAME }} --version ${{env.BB_VERSION}}
 
-      - name: Upload Artifact Ubuntu ARM64
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.BB_ARTIFACT_NAME }}
-          path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME }}
-          if-no-files-found: error
+  #     - name: Upload Artifact Ubuntu ARM64
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BB_ARTIFACT_NAME }}
+  #         path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME }}
+  #         if-no-files-found: error
 
-      - name: Build Bladebit CUDA
-        run: |
-          .github/actions/build-asset-unix.sh --cuda --artifact ${{ env.BB_ARTIFACT_NAME_CUDA }} --version ${{ env.BB_VERSION }}
-      - name: Upload Bladebit CUDA Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.BB_ARTIFACT_NAME_CUDA }}
-          path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME_CUDA }}
-          if-no-files-found: error
+  #     - name: Build Bladebit CUDA
+  #       run: |
+  #         .github/actions/build-asset-unix.sh --cuda --artifact ${{ env.BB_ARTIFACT_NAME_CUDA }} --version ${{ env.BB_VERSION }}
+  #     - name: Upload Bladebit CUDA Artifact
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.BB_ARTIFACT_NAME_CUDA }}
+  #         path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME_CUDA }}
+  #         if-no-files-found: error
 
   build-bladebit-windows-x86-64:
     runs-on: windows-2019
